# <center>Data cleaning</center>

Now keep in mind, I had to reduce the data in order to have enough memory to run the KNN imputer. So for now, we will use
10% of our data. I will do it here instead of long data because all IDs are unique and we make sure we will get all years
data for each ID.

In [2]:
import pandas as pd
import numpy as np

## Load dataset

In [18]:
# load dataset
pd_df = pd.read_csv(r"C:\Your_Path\long_clean_df.csv")

In [19]:
pd_df.shape

(23106, 922)

In [20]:
#Sorry but you'll have to take my word for this - because this dataset contains actual
#variables from a big healthcare dataset, I had to randomly assign simply a number for each
#column/feature

# Just know that Index 0 = ID, Index 1 = Time (years 0, 3, or 6), and Index 105 = Congestive Heart Failure at year 6 (0=no; 1=yes)
numvar_names = np.arange(0,922,1)
numvar_names=list(numvar_names)
numvar_names

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921]

In [21]:
pd_df.columns = numvar_names
pd_df

,0,1,2,3,4,5,6,7,8,9,...,912,913,914,915,916,917,918,919,920,921
0,100104.0,0,0.0,0.0,0.0,0.0,1.0,79.0,3.0,4.0,...,0.00930,0.05206,1.74573,15.84713,0.00940,0.08427,0.46214,0.00336,0.25476,0.00610
1,100104.0,3,0.0,0.0,0.0,0.0,1.0,79.0,3.0,4.0,...,0.00768,0.06404,1.22217,11.73960,0.00635,0.25200,1.01635,0.00331,0.48335,0.00071
2,100104.0,6,0.0,0.0,0.0,0.0,1.0,79.0,3.0,4.0,...,0.00768,0.06404,1.22217,11.73960,0.00635,0.25200,1.01635,0.00331,0.48335,0.00071
3,100155.0,0,0.0,0.0,0.0,0.0,1.0,58.0,1.0,2.0,...,0.01838,0.08562,1.36348,11.82454,0.00324,0.07100,0.39003,0.00005,0.41287,0.01848
4,100155.0,3,0.0,0.0,0.0,0.0,1.0,58.0,1.0,2.0,...,0.01223,0.06208,0.85739,7.59533,0.00926,0.06857,0.36516,0.00515,0.35961,0.02085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23101,299947.0,0,0.0,0.0,0.0,0.0,1.0,55.0,1.0,2.0,...,0.01866,0.08500,3.99463,29.44423,0.00000,0.02800,0.19334,0.00000,0.21249,0.00150
23102,299947.0,6,0.0,0.0,0.0,0.0,1.0,55.0,1.0,2.0,...,0.04485,0.16151,3.18033,25.89818,0.05047,0.04267,0.20580,0.00075,0.13210,0.01653
23103,299991.0,3,0.0,0.0,0.0,0.0,1.0,69.0,2.0,3.0,...,0.00784,0.03839,0.47641,3.75133,0.00559,0.03288,0.14635,0.00473,0.07905,0.00831
23104,299991.0,0,0.0,0.0,0.0,0.0,1.0,69.0,2.0,3.0,...,0.00543,0.01836,0.79863,5.83042,0.00365,0.16936,0.57916,0.00506,0.25674,0.00399
23105,299991.0,6,0.0,0.0,0.0,0.0,1.0,69.0,2.0,3.0,...,0.00784,0.03839,0.47641,3.75133,0.00559,0.03288,0.14635,0.00473,0.07905,0.00831

In [36]:
# check dataset imbalance, which is our CHF variable now renamed to '104' since index is 105.
# We see that, the current 10% slice of our original data (230k entries) is 1.09% cases, 
# which is basically equivalent to the true positive of 1.01% for 230k entries

yes = float(pd_df.iloc[:,[105]].sum()) #selects the column '104', which is our var that defines heart failure status, which is also index 105 used here.
total = float(pd_df.iloc[:,[105]].count())
print('Examples:\n    Total: {}\n    Positive: {} ({:.2f}% of total)\n'.format(int(total), int(yes), 100 * yes / total))

Examples:
    Total: 23106
    Positive: 253 (1.09% of total)

In [37]:
#Now that we confirm our outcome is roughly the same balance (or imbalanced) as our original dataset (1% vs original 1.05%)
#Let's convert data to array for easier processing and reduced memory use
pd_dfarray = pd_df.to_numpy()
pd_dfarray

array([[1.00104e+05, 0.00000e+00, 0.00000e+00, ..., 3.36000e-03,
        2.54760e-01, 6.10000e-03],
       [1.00104e+05, 3.00000e+00, 0.00000e+00, ..., 3.31000e-03,
        4.83350e-01, 7.10000e-04],
       [1.00104e+05, 6.00000e+00, 0.00000e+00, ..., 3.31000e-03,
        4.83350e-01, 7.10000e-04],
       ...,
       [2.99991e+05, 3.00000e+00, 0.00000e+00, ..., 4.73000e-03,
        7.90500e-02, 8.31000e-03],
       [2.99991e+05, 0.00000e+00, 0.00000e+00, ..., 5.06000e-03,
        2.56740e-01, 3.99000e-03],
       [2.99991e+05, 6.00000e+00, 0.00000e+00, ..., 4.73000e-03,
        7.90500e-02, 8.31000e-03]])

In [40]:
#scaling mandatory before knn

from sklearn.preprocessing import MinMaxScaler
from pickle import dump

scaler = MinMaxScaler()

X_norm = pd.DataFrame(scaler.fit_transform(pd_df))

# save the scaler
dump(scaler, open('scaler.pkl', 'wb'))

In [41]:
X_norm

,0,1,2,3,4,5,6,7,8,9,...,912,913,914,915,916,917,918,919,920,921
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.023887,0.019026,0.145671,0.177484,0.045919,0.290256,0.006079,0.016926,0.002429,0.000603
1,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.019726,0.023405,0.100943,0.130860,0.031019,0.867978,0.013368,0.016674,0.004609,0.000070
2,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.019726,0.023405,0.100943,0.130860,0.031019,0.867978,0.013368,0.016674,0.004609,0.000070
3,0.000255,0.0,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.047209,0.031291,0.113015,0.131824,0.015827,0.244549,0.005130,0.000252,0.003937,0.001828
4,0.000255,0.5,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.031413,0.022688,0.069779,0.083819,0.045235,0.236180,0.004803,0.025943,0.003429,0.002063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23101,0.999780,0.0,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.047928,0.031065,0.337799,0.331823,0.000000,0.096442,0.002543,0.000000,0.002026,0.000148
23102,0.999780,1.0,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.115198,0.059027,0.268232,0.291572,0.246544,0.146971,0.002707,0.003778,0.001260,0.001635
23103,1.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.020137,0.014030,0.037231,0.040186,0.027307,0.113250,0.001925,0.023828,0.000754,0.000822
23104,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.013947,0.006710,0.064759,0.063786,0.017830,0.583336,0.007618,0.025490,0.002448,0.000395
23105,1.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.020137,0.014030,0.037231,0.040186,0.027307,0.113250,0.001925,0.023828,0.000754,0.000822

In [42]:
X_norm_array = X_norm.to_numpy()
X_norm_array
print(X_norm.shape)
print(X_norm_array.shape)

(23106, 922)
(23106, 922)

# Imputation of Xs with KNN

In [43]:
## https://towardsdatascience.com/make-knn-300-times-faster-than-scikit-learns-in-20-lines-5e29d74e76bb
# import numpy as np
# import faiss

# class FaissKNeighbors:
#     def __init__(self, k=5):
#         self.index = None
#         self.y = None
#         self.k = k

#     def fit(self, X, y):
#         self.index = faiss.IndexFlatL2(X.shape[1])
#         self.index.add(X.astype(np.float32))
#         self.y = y

#     def predict(self, X):
#         distances, indices = self.index.search(X.astype(np.float32), k=self.k)
#         votes = self.y[indices]
#         predictions = np.array([np.argmax(np.bincount(x)) for x in votes])
#         return predictions

In [44]:
#knn imputer

from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3)

X_knn = imputer.fit_transform(X_norm_array)

In [45]:
X_knn

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.69260994e-02, 2.42916833e-03, 6.03431050e-04],
       [0.00000000e+00, 5.00000000e-01, 0.00000000e+00, ...,
        1.66742230e-02, 4.60880245e-03, 7.02354172e-05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.66742230e-02, 4.60880245e-03, 7.02354172e-05],
       ...,
       [1.00000000e+00, 5.00000000e-01, 0.00000000e+00, ...,
        2.38275150e-02, 7.53751595e-04, 8.22051151e-04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.54898998e-02, 2.44804787e-03, 3.94703260e-04],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        2.38275150e-02, 7.53751595e-04, 8.22051151e-04]])

In [137]:
print(X_knn.shape)
# This shows the shape of our imputed dataset, which its first dimension has 23106 elements (participants)
# And for each participant, there are 922 more elements (which are the values for the 922 variables in our dataset)

(23106, 922)

In [46]:
# Let's now check if there are still any variables missing to see if our imputation worked correctly.
# We should see no more missing values and thus our boolean should return false.

X_knn_sum = np.sum(X_knn)
X_knn_has_nan = np.isnan(X_knn_sum)
X_knn_has_nan

False

In [47]:
# Let's now convert our data first back to pandas data frame so that we may add the column headers back
# We will need to do this to remove our Index variable (0), time variable (1), and outcome variable heart failure (105)
# Doing this is the first step of creating our training dataset X_train

X_knn_arrayconvert = pd.DataFrame(X_knn, columns = np.arange(922))
X_knn_arrayconvert

,0,1,2,3,4,5,6,7,8,9,...,912,913,914,915,916,917,918,919,920,921
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.023887,0.019026,0.145671,0.177484,0.045919,0.290256,0.006079,0.016926,0.002429,0.000603
1,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.019726,0.023405,0.100943,0.130860,0.031019,0.867978,0.013368,0.016674,0.004609,0.000070
2,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.019726,0.023405,0.100943,0.130860,0.031019,0.867978,0.013368,0.016674,0.004609,0.000070
3,0.000255,0.0,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.047209,0.031291,0.113015,0.131824,0.015827,0.244549,0.005130,0.000252,0.003937,0.001828
4,0.000255,0.5,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.031413,0.022688,0.069779,0.083819,0.045235,0.236180,0.004803,0.025943,0.003429,0.002063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23101,0.999780,0.0,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.047928,0.031065,0.337799,0.331823,0.000000,0.096442,0.002543,0.000000,0.002026,0.000148
23102,0.999780,1.0,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.115198,0.059027,0.268232,0.291572,0.246544,0.146971,0.002707,0.003778,0.001260,0.001635
23103,1.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.020137,0.014030,0.037231,0.040186,0.027307,0.113250,0.001925,0.023828,0.000754,0.000822
23104,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.013947,0.006710,0.064759,0.063786,0.017830,0.583336,0.007618,0.025490,0.002448,0.000395
23105,1.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.020137,0.014030,0.037231,0.040186,0.027307,0.113250,0.001925,0.023828,0.000754,0.000822

In [48]:
#Now let's remove the columns ID, year, and CHF for preparation of imputation

#First, we will only keep values from baseline (0) and year 3 (0.5).
X_knn_arrayconvert1 = X_knn_arrayconvert[X_knn_arrayconvert[1] != 1.0]
X_knn_arrayconvert1

,0,1,2,3,4,5,6,7,8,9,...,912,913,914,915,916,917,918,919,920,921
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.023887,0.019026,0.145671,0.177484,0.045919,0.290256,0.006079,0.016926,0.002429,0.000603
1,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,1.000000,...,0.019726,0.023405,0.100943,0.130860,0.031019,0.867978,0.013368,0.016674,0.004609,0.000070
3,0.000255,0.0,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.047209,0.031291,0.113015,0.131824,0.015827,0.244549,0.005130,0.000252,0.003937,0.001828
4,0.000255,0.5,0.0,0.0,0.0,0.0,0.0,0.275862,0.0,0.333333,...,0.031413,0.022688,0.069779,0.083819,0.045235,0.236180,0.004803,0.025943,0.003429,0.002063
6,0.000290,0.0,0.0,0.0,0.0,0.0,0.0,0.965517,1.0,1.000000,...,0.005574,0.004554,0.018768,0.020354,0.003810,0.048290,0.001774,0.005441,0.001086,0.000572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23098,0.999540,0.0,0.0,0.0,0.0,0.0,0.0,0.896552,1.0,1.000000,...,0.020240,0.019384,0.054482,0.070939,0.008939,0.049461,0.000981,0.012745,0.000488,0.000359
23100,0.999780,0.5,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.115198,0.059027,0.268232,0.291572,0.246544,0.146971,0.002707,0.003778,0.001260,0.001635
23101,0.999780,0.0,0.0,0.0,0.0,0.0,0.0,0.172414,0.0,0.333333,...,0.047928,0.031065,0.337799,0.331823,0.000000,0.096442,0.002543,0.000000,0.002026,0.000148
23103,1.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.020137,0.014030,0.037231,0.040186,0.027307,0.113250,0.001925,0.023828,0.000754,0.000822
23104,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.655172,0.5,0.666667,...,0.013947,0.006710,0.064759,0.063786,0.017830,0.583336,0.007618,0.025490,0.002448,0.000395

In [49]:
# Now let's drop our 3 columns so that we have only the features used for predictions in our training data.
X_data_initial = X_knn_arrayconvert1.drop(X_knn_arrayconvert1.columns[[0, 1, 105]], axis=1)

In [50]:
# We can check that with those 3 columns dropped we have only 919 columns left.

X_data_initial_array = X_data_initial.to_numpy()
X_data_initial_array.shape

(15404, 919)

In [51]:
X_data = X_data_initial_array.reshape(7702, 2, 919)
print(X_data.shape)

# This reshapes our initial training data shape from (15,404, 919)
# to (7702, 2, 919) which is mainly so that the sequential model we will run later can have the appropriate input shape (2, 919).

# To go a bit more in detail here, our initial data was 2 dimensions. First dimension has 15404 elements (aka persons, IDs).
# And in each of those elements/IDs we have 919 more elements (aka values for the 919 features).

# It is then reshaped into a 3-dimensional array, with first dimension of 7702 elements (IDs).
# Each of those 7702 elements has 2 additional elements (2 time points Time 0 and Time 3).
# Within each of those 2 elements/times, there are 919 elements (values for the 919 features).

(7702, 2, 919)

# Now let's create our heart failure outcome dataset (Y)

In [52]:
# Take our deleted columns and now keep only those at year 6 (time = 1.0)
Y = X_knn_arrayconvert[[0, 1, 105]][X_knn_arrayconvert[1] == 1.0]

In [53]:
Y

            0    1    105
2      0.000000  1.0  0.0
5      0.000255  1.0  0.0
8      0.000290  1.0  0.0
9      0.000295  1.0  0.0
14     0.000500  1.0  0.0
...         ...  ...  ...
23093  0.999380  1.0  0.0
23096  0.999490  1.0  0.0
23099  0.999540  1.0  0.0
23102  0.999780  1.0  0.0
23105  1.000000  1.0  0.0

[7702 rows x 3 columns]

In [55]:
# Like our X_train data, we need to convert them also into an numpy array
Y_array = Y[[105]].to_numpy()
display(Y_array)
print(Y_array.shape)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

(7702, 1)

In [56]:
# To again properly shape this into an acceptable format so that sequential model can run, we reshape this into a 3D array.
Y_data = Y_array.reshape(7702, 1, 1)
print(Y_data.shape)
display(Y_data)

(7702, 1, 1)

array([[[0.]],

       [[0.]],

       [[0.]],

       ...,

       [[0.]],

       [[0.]],

       [[0.]]])

In [57]:
# Let's also see whether we have any more missing values for outcomes.

Y_array_sum = np.sum(Y_data)
Y_array_has_nan = np.isnan(Y_array_sum)
Y_array_has_nan

False

# Save data

##### Now that our data is in array form and also in correct dimensions, we will save it. In the next file, we will use this data to produce the results of our LSTM models and other variations.

In [174]:
# save numpy array as npy file
from numpy import save
# save to npy file
save(r'C:\Your_Path\X_data.npy', X_data)
save(r'C:\Your_Path\Y_data.npy', Y_data)